services:
  faux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faux
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-PROD}
      - PORT=${PORT:-8080}
    restart: unless-stopped
